repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
        language_version: python3
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
          - --line-length
          - '79'
